### ISSUE TITLE
Change Jira's Bugzilla links to use the Bugzilla favicon and URL instead of a generic globe icon and "Bugzilla Ticket" title

### ISSUE THREAD

**Issue by cpeterso** [mozilla/jira-bugzilla-integration#202] opened 2022-08-13 00:24 UTC
Enhancement suggestion:

When JBI links a Jira issue to its corresponding Bugzilla bug, the Jira issue's web link has a default globe icon and the generic title `Bugzilla Ticket`:

![image](https://user-images.githubusercontent.com/629193/184459591-0865de09-3987-48ae-8710-f54d14855408.png)

I think this makes visually finding the Bugzilla link on the busy Jira page harder than it needs to be. I think it would be more useful if the Bugzilla web link's favicon was Bugzilla's green bug favicon and showed the bug's full Bugzilla URL (or something descriptive like `Bugzilla bug 1234567`) instead of `Bugzilla Ticket`. The Bugzilla favicon and URL are shown by default when a user manually adds a Bugzilla link to a Jira issue:

![image](https://user-images.githubusercontent.com/629193/184459622-544ade8f-63dd-434e-aa59-a13c3feccf48.png)

**Comment by mostlygeek** [comment] 2022-08-13 00:49
@bsieber-mozilla any idea if this is even possible via the Jira API?

**Comment by grahamalama** [comment] 2022-08-15 14:41
Hmm, is this a regression? https://github.com/mozilla/jira-bugzilla-integration/pull/159

**Comment by bsieber-mozilla** [comment] 2022-08-15 17:11
@mostlygeek we've got some options to enhance the look of the remote-link.

I think it might be best to scrap adding a title to the remote-link and instead just use the URL? I think that jira might be capable enough to see a "bugzilla" domain and add the favicon (like the manual approach).

**Comment by grahamalama** [comment] 2022-08-15 17:19
@bsieber-mozilla it looks like that's what's still on `main` [at the moment](https://github.com/mozilla/jira-bugzilla-integration/blob/a9e3d2cdae3c5cf5ea740e5766a0397dcf77748a/jbi/actions/default.py#L270).

Maybe this ticket just hasn't been updated in a while, so that why the old `Bugzilla Ticket` link title is still there?

But I do like
> scrap adding a title to the remote-link and instead just use the URL

If that means the favicon will show up

**Comment by bsieber-mozilla** [comment] 2022-08-15 20:46
It looks like title and url are required. I'll do a local test to see if having the title=url will pull this thumbnail for users. Otherwise, there are more advanced properties we can modify with the API.

https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-remote-links/#api-rest-api-3-issue-issueidorkey-remotelink-post

**Comment by bsieber-mozilla** [comment] 2022-08-18 18:35
To follow-up here... Although it's possible with the REST API to add an icon, the functionality is not yet in the current jira service python api. When attempting to just provide the URL via the API, the icon is not auto-fetched (unlike when manually adding the link).

**Comment by grahamalama** [comment] 2022-08-26 19:33
Closed via #207. Thanks @bsieber-mozilla 📷 🐛

**Closed by grahamalama** 2022-08-26 19:33 UTC
