### ISSUE TITLE
Add JBI sync from Buzilla to Jira OMC project

### ISSUE THREAD

**Issue by RoMan-moz** [mozilla/jira-bugzilla-integration#525] opened 2023-05-22 14:59 UTC
The Onboarding, Messaging, and Communication team would like to set up a sync from Bugzilla to Jira. The Product: Firefox, Component: Messaging System, Platform: Desktop, & Triage Owner: lsmith.

**Comment by grahamalama** [comment] 2023-05-24 15:53
Confirmed with @RoMan-moz that `[omc]` is the whiteboard tag he wants to use

**Comment by grahamalama** [comment] 2023-05-24 16:00
I did not create a new webhook to support this sync since a webhook already exists for the Firefox Product, scoped to all components

<img width="1003" alt="image" src="https://github.com/mozilla/jira-bugzilla-integration/assets/20747904/9ded1a14-01b5-4273-b90b-9ed8fba4bf60">

**Comment by grahamalama** [comment] 2023-05-24 16:08
Also some disucssion with @RoMan-moz about this ticket and workflow:

@RoMan-moz primarily uses a "Jira first" workflow. Tickets on the FXE board trigger the creation of some tickets on the OMC board. When that happens, a "companion" bug is manually created in Bugzilla.

The goal of enabling this workflow is to sync activity on the "companion" bug back to the Jira ticket.

To allow for this, when the Bugzilla bug is manually created, the whiteboard tag will be set to `[omc]` _and_ the `see_also` field will be set to the URL of the Jira ticket.

**Comment by RoMan-moz** [comment] 2023-05-25 20:43
Hey Graham, :confounded: I screwed up!!!!
I need to have the Jira ticket info in the URL: field, not the See Also: field. Do I need to file another Github ticket to make that change? Also, I have two tickets that can be used for testing. I've added comments to the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1834642) but they are not showing up in [Jira](https://mozilla-hub.atlassian.net/browse/OMC-445) yet. I manually added the bug to the Jira

**Comment by grahamalama** [comment] 2023-05-25 20:44
Hey @RoMan-moz, your config config was initially supposed to go live today with the [v4.4.0](https://github.com/mozilla/jira-bugzilla-integration/releases/tag/v4.4.0) release, but we had to roll that back because we encountered a few bugs that we need to squash. Your config will go out in the next release.

**Comment by RoMan-moz** [comment] 2023-05-25 20:44
Okay, so there's time to make this change then?

**Comment by grahamalama** [comment] 2023-05-25 20:50
As for

> I need to have the Jira ticket info in the URL: field, not the See Also: field. 

JBI only supports adding the Jira ticket link to the `See Also` field, unfortunately. Do note that you can add multiple URLs to the `See Also` field, so the Jira issue can be one of many links there.

> Can you let me know when it goes to Release so I can test it?
Yes, we'll update you when this config gets merged to production.

**Comment by RoMan-moz** [comment] 2023-05-30 16:05
Hey @leplatrem , I just tested it and it works great! Yay!!!
As for having Bugzilla file a new Jira ticket if we don't already have one to link to, yes, it would be best if the new ticket had the Status of "To Do". Thanks for all you've done on getting this completed.

**Comment by leplatrem** [comment] 2023-06-01 14:10
@RoMan-moz shall we map all statuses to "To Do"? or just those with status `UNCONFIRMED` and `NEW`?

**Comment by RoMan-moz** [comment] 2023-06-06 14:51
Can we just do those with the status UNCONFIRMED and NEW?

**Closed** 2023-06-12 16:17 UTC
Labels: configuration
